### ISSUE TITLE
backend is not loading 

### ISSUE THREAD

**Issue by MyPenOnline** [todordev/ITPGoogleSearch#1]
i have installed the component in joomla 3.0.3 but the back end of the component is not opening in /administrator/index.php?option=com_itpgooglesearch

**Comment by todordev** [comment]
Hi,
Thank you for the post!
could you enable Joomla! debug from "Global Configuration"? 
Let's see what will display as error.
You can also check error log in folder "logs/".

**Comment by MyPenOnline** [comment]
sorry i am trying but no error logs found

**Comment by todordev** [comment]
The extension has only "Options". Do you see the button "Options" on the left top side?

**Comment by MyPenOnline** [comment]
the page is not loading 
its blank
even the page source is blank

**Comment by todordev** [comment]
could you send me username and password to todor@itprism.com? 
I would like to see it.
Thank you!

**Comment by MyPenOnline** [comment]
you need backend access

**Comment by todordev** [comment]
yeap

**Comment by MyPenOnline** [comment]
administrator privilege is enough or you need super administrator

**Comment by todordev** [comment]
administrator is enough. 
I just want to see the extension. 
please enable debug mode.

**Comment by todordev** [comment]
you can enable debug mode and set "Error Reporting" to maximum. that will display the error.

**Comment by bradkelleykc** [comment]
It's dying because the component is using DS for directory separators, and that is no longer supported. To alleviate this, change occurrences of ". DS .", ".DS.", and ". DS." to ". DIRECTORY_SEPARATOR ." More on this here: http://forum.joomla.org/viewtopic.php?p=2720756
![screen shot 2013-09-13 at 11 42 20 am](https://f.cloud.github.com/assets/5453754/1139995/a04c86f4-1c96-11e3-80f0-4c61818a38a2.png)
![screen shot 2013-09-13 at 11 41 13 am](https://f.cloud.github.com/assets/5453754/1139994/a04b6e40-1c96-11e3-9c80-1efc07f81aa4.png)

**Comment by todordev** [comment]
Hi,
Thank you very much for the post!
I have just fixed it.
You can download the latest version now.
http://itprism.com/free-joomla-extensions/others/google-search-integration

Best regards,
Todor
